name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: pwd
    
  DeployDev:
    name: Deploy to Dev 
    #if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: self-hosted
    environment: 
      name: Development
    steps:
      - name: Deploy
        run: pwd
    
  DeployQA:
    name: Deploy to QA 
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: self-hosted
    environment: 
      name: QA
    steps:
      - name: Deploy
        run: pwd
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployQA]
    runs-on: self-hosted
    environment: 
      name: Production
    steps:
      - name: Deploy
        run: pwd
